### PR TITLE
[CI] Build on JS and WASM backends

### PR DESCRIPTION
**Pull request by konsumlamm**
Running the tests doesn't work currently, but building the library does. I took the build steps from https://www.haskell.org/ghcup/guide/#cross-support. Should the actions also cache stuff? If so, could one just copy the caching from the `build` job?

Also rename `ci.yml` to `ci.yaml` ([`.yaml` is the recommended extension](https://yaml.org/faq)).

### CODE REVIEW

**Comment by Bodigrim** [comment]
Thanks!

> Running the tests doesn't work currently, but building the library does.

What's failing in tests?

> Should the actions also cache stuff? If so, could one just copy the caching from the build job?

Caching would be nice. Yes, presumably you can copy it from the main build job, just adjust cache key.

**Comment by konsumlamm** [comment]
> > Running the tests doesn't work currently, but building the library does.
> 
> What's failing in tests?

On the JS backend, the tests fail to run due to `ReferenceError: h$getMonotonicNSec is not defined` (see https://gitlab.haskell.org/ghc/ghc/-/issues/22374) and on the WASM backend, `semirings` fails to compile (https://github.com/chessai/semirings/pull/86). See https://github.com/konsumlamm/bitvec/actions/runs/7029803339 for logs.

**Comment by konsumlamm** [comment]
Still a linker error:
```
wasm-ld: error: /home/runner/.local/state/cabal/store/ghc-9.8.0.20230927/splitmix-0.1.0.5-ca7fbe7591ee007f80e9a34938251542fa964d5342dbfb81ee20559bbbf44ea3/lib/libHSsplitmix-0.1.0.5-ca7fbe7591ee007f80e9a34938251542fa964d5342dbfb81ee20559bbbf44ea3.a(init.o): undefined symbol: clock
wasm-ld: error: /home/runner/.local/state/cabal/store/ghc-9.8.0.20230927/splitmix-0.1.0.5-ca7fbe7591ee007f80e9a34938251542fa964d5342dbfb81ee20559bbbf44ea3/lib/libHSsplitmix-0.1.0.5-ca7fbe7591ee007f80e9a34938251542fa964d5342dbfb81ee20559bbbf44ea3.a(init.o): undefined symbol: getpid
```

**Comment by Bodigrim** [comment]
That's https://github.com/haskellari/splitmix/pull/73, one can workaround as in `zlib`. See
* https://github.com/haskell/zlib/blob/add586898fd38712980731f2f3a13ce8d75650aa/cabal.project.wasi
* https://github.com/haskell/zlib/blob/add586898fd38712980731f2f3a13ce8d75650aa/.github/workflows/other.yml#L43

**Comment by TerrorJack** [comment]
the `-lHSrts-1.0.2_thr` error is indeed because we don't build the threaded rts for wasm at all. as for `clock`, `getpid`, yes, it's necessary to use those workarounds for the time being.

**Comment by konsumlamm** [comment]
Now the tests finally run (and pass) under WASM.

**Comment by Bodigrim** [comment]
Awesome, many thanks!

**Pull request merged**
